# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a2b9be8b377473e75ff6d5ad9928a8eda76f792468bf500f7833887107705554fda161717db49a61f3ec9d642effdf016b06b14e9be34b34df894bc0e7fe8b6c

test:
  secret_key_base: fbfe187c6cd37b1db54ae709c79aaf9968dc70645adf38c43c82cbeaafb44ecfb5c6b1fc098c37e619291ce716faf92a6b35c5bd0f7fda1b02183c23325611d8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
